# Generated by Django 4.2.5 on 2024-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/userProfile/user.png', null=True, upload_to='profile/'),
        ),
    ]
