# Generated by Django 4.2.5 on 2024-03-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_forward_related_chat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
