# Generated by Django 4.2.5 on 2024-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_paticipants_group_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default/groupProfile', null=True, upload_to='GroupProfile'),
        ),
    ]
