# Generated by Django 4.2.5 on 2024-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forward',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default/groupProfile/group-profile.png', null=True, upload_to='GroupProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
