# Generated by Django 4.2.5 on 2024-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_forward_timestamp_alter_group_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commentcontainer',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
