# Generated by Django 4.2.5 on 2024-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_follower_followed_alter_follower_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default/groupProfile/group.png', null=True, upload_to='GroupProfile'),
        ),
    ]
