# Generated by Django 4.2.5 on 2024-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_groupadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadmin',
            name='creation_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
