# Generated by Django 4.2.5 on 2024-03-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_groupadmin_creation_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupadmin',
            unique_together={('user', 'group')},
        ),
    ]
