# Generated by Django 4.2.5 on 2024-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_game_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
