# Generated by Django 4.2.5 on 2024-03-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_chatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatimage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
