# Generated by Django 4.2.5 on 2024-03-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_chatimage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.DeleteModel(
            name='ChatImage',
        ),
    ]
