# Generated by Django 4.2.5 on 2024-05-18 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_forward_image_message_image_delete_chatimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='message_seens', to=settings.AUTH_USER_MODEL),
        ),
    ]
